# Generated by Django 4.2.7 on 2023-11-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tema', models.CharField(choices=[('ação', 'Ação'), ('terror', 'Terror'), ('rpg', 'RPG'), ('sobrevivência', 'Sobrevivência'), ('enigma', 'Enigma'), ('corrida', 'Corrida')], max_length=20)),
                ('descricao', models.TextField()),
                ('sistema_avaliacao', models.FloatField()),
            ],
        ),
    ]
