# Generated by Django 5.0.6 on 2024-06-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='codigo_midia_digital',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
