# Generated by Django 4.2.7 on 2023-11-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='codigo_midia_digital',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
