# Generated by Django 4.2.7 on 2023-11-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jogo_codigo_midia_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='no_carrinho',
            field=models.BooleanField(default=False),
        ),
    ]
